#!/bin/bash
# Generates the scripts required to perform a CodeDeploy deployment
# for your project.
set -eou pipefail

SCRIPT_DIR=$(dirname $0)

# VARIABLES
AWS_REGION="$1"; shift
IMAGE="$1"; shift
SERVICE="$1"; shift
CLUSTER="$1"; shift
TASK_DEF="$1"; shift
DOCKER_ROOT="$1"; shift
DOCKER_PARENT="$1"; shift
DEPLOY_APP="$1"; shift
DEPLOY_GRP="$1"; shift
DEPLOY_SPEC="$1"; shift
DEPLOYMENT_FOLDER="$1"; shift
ENVIRONMENT="$1"; shift
APP_NAME="$1"; shift

FILE_TASK_DEF="${DEPLOYMENT_FOLDER}/${ENVIRONMENT}/task-def.json"
FILE_DEPLOY_SPEC="${DEPLOYMENT_FOLDER}/${ENVIRONMENT}/deploy-spec.json"

mkdir -p ${DEPLOYMENT_FOLDER}/${ENVIRONMENT}
cat <<EOF > ${DEPLOYMENT_FOLDER}/${ENVIRONMENT}/conf.sh
# deploy.conf
# Automatically generated by Terraform ECS HA module.
# Do not manually edit this file unless you know what you're doing.

CWD=\$(pwd)
AWS_REGION=${AWS_REGION?"Not defined"}
DOCKER_FOLDER=${DOCKER_ROOT?"Not defined"}
DOCKER_IMAGE=${IMAGE?"Not defined"}
DOCKER_PARENT=${DOCKER_PARENT}
ECS_SERVICE=${SERVICE?"Not defined"}
ECS_CLUSTER=${CLUSTER?"Not defined"}
ECS_DEPLOY_APP=${DEPLOY_APP?"Not defined"}
ECS_DEPLOY_GRP=${DEPLOY_GRP?"Not defined"}
ECS_FILE_TASK_DEF=\${CWD}/${ENVIRONMENT}/task-def.json
ECS_FILE_DEPLOY_SPEC=\${CWD}/${ENVIRONMENT}/deploy-spec.json
APP_NAME=${APP_NAME}
ENVIRONMENT=${ENVIRONMENT}
EOF

echo "${TASK_DEF}" > ${FILE_TASK_DEF}
echo "${DEPLOY_SPEC}" > ${FILE_DEPLOY_SPEC}

cp ${SCRIPT_DIR}/aws-deployment-generator-script.sh ${DEPLOYMENT_FOLDER}/deploy.sh
chmod +x ${DEPLOYMENT_FOLDER}/deploy.sh

echo "Deployment folder updated: ${DEPLOYMENT_FOLDER}"
exit 0